### PR TITLE
Hactoberfest2022--> fibonacci_series.java

### PR DESCRIPTION
**Pull request by Abhinav092003**
fibonacci series in java
added comments for better understanding..
please approve me

### CODE REVIEW

**Comment by Abhinav092003** [comment]
maintainer please accept me please🙏🙏

**Comment by Pavan-Kamthane** [comment]
Make a separate folder

**Comment by Pavan-Kamthane** [comment]
Star this repo

**Comment by Abhinav092003** [comment]
Done👍👍please accept my issue

**Pull request merged**
